--- # Build an Apache Web Server
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: When did the ROLE start
    raw: date > /home/ansible/startofrole.log
  roles:
  - { role: redhat.apachewebserver, when: "ansible_os_family == 'RedHat'" }
  - { role: debian.apachewebserver, when: "ansible_os_family == 'Debian'" }
  post_tasks:
  - name: When did the ROLE end
    raw: date > /home/ansible/endodrole.log
